#!/usr/bin/env node

const amqp = require('amqplib/callback_api');
const params = process.argv.slice(2);
amqp.connect('amqp://localhost', function(err, conn) {
  conn.createChannel(function(err, ch) {
    var q = 'hello';
    var msg = JSON.stringify({
      email: params[0] ? params[0] : "",
      subject: params[1] ? params[1] : "",
      body: params[2] ? params[2] : ""
    });

    ch.assertQueue(q, {durable: false});
    ch.sendToQueue(q, new Buffer(msg));
    console.log(" [x] Sent %s", msg);
  });
  setTimeout(function() { conn.close(); process.exit(0) }, 500);
});
