#!/usr/bin/env node

const nodemailer = require('nodemailer');
let transporter = nodemailer.createTransport({
 host: 'smtp.ukr.net',
 port: 465,
 secure: true,
 auth: {
        user: 'madi.nickname@ukr.net',
        pass: '21012008'
    }
});


module.exports = transporter;
/*const mailOptions = {
  from: 'madi.nickname@ukr.net', // sender address
  to: 'madi.nickname@gmail.com', // list of receivers
  subject: 'Subject of your email', // Subject line
  html: '<p>Your html here</p>'// plain text body
};
transporter.sendMail(mailOptions, function (err, info) {
   if(err)
     console.log(err)
   else
     console.log(info);
});*/
